# Generated by Django 4.1 on 2023-06-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='461f5fa7', max_length=10, unique=True),
        ),
    ]
