# Generated by Django 4.2.1 on 2023-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='60ac30c5', max_length=10, unique=True),
        ),
    ]
