# Generated by Django 4.1 on 2023-06-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='ead9071e', max_length=10, unique=True),
        ),
    ]
