# Generated by Django 4.1 on 2023-09-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_order_user_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='4b5f2530', max_length=10, unique=True),
        ),
    ]
